### ISSUE TITLE
panic using trace in client

### ISSUE THREAD

**Issue by sillydong** [micro/go-os#38]
when I tried to use trace in client, I got panic for assignment to entry in nil map. After I dig into the code I found that the md return by metadata.FromContext cound be nil.

https://github.com/micro/go-os/blob/master/trace/wrapper.go

    func (c *clientWrapper) Call(ctx context.Context, req client.Request, rsp interface{}, opts ...client.CallOption) error {
        var span *Span
        var ok, okk bool
        var err error

        md, mk := metadata.FromContext(ctx)          //md can be nil

https://github.com/micro/go-micro/blob/master/metadata/metadata.go

    func FromContext(ctx context.Context) (Metadata, bool) {
        md, ok := ctx.Value(metaKey{}).(Metadata)     //what should i do to avoid returning nil
        return md, ok
    }

what should I do?

**Comment by asim** [comment]
Where is the actual panic? Is it in your code? Is it in the wrapper? Do you have a stack trace? If you are using FromContext directly, it's returning a bool to tell you whether metadata was found. If the bool is false assume metadata is nil.

**Comment by sillydong** [comment]
I used the following test code:

    import (
        "testing"
        "github.com/micro/go-os/trace"
        "github.com/micro/go-micro/client"
        "github.com/micro/go-micro/registry"
        "golang.org/x/net/context"
        "github.com/micro/user-srv/proto/account"
    )

    func TestRequest(t *testing.T) {
        srv := &registry.Service{Name:"go.api.test"}
        tr := trace.NewTrace()
        c := client.NewClient(
            client.Wrap(trace.ClientWrapper(tr, srv)),
        )
        
        srvclient := account.NewAccountClient("go.micro.srv.user", c)
        req := account.ReadRequest{Id:"qwer"}
        resp, err := srvclient.Read(context.TODO(), &req)
        if err != nil {
            t.Error(err)
        }else {
            t.Logf("%+v", resp.User)
        }
    }

panic content is here:

    === RUN   TestRequest
    --- FAIL: TestRequest (0.00s)
    panic: assignment to entry in nil map [recovered]
            panic: assignment to entry in nil map

    goroutine 21 [running]:
    panic(0x3b5900, 0xc420077af0)
            /usr/local/go1.7/src/runtime/panic.go:500 +0x1a1
    testing.tRunner.func1(0xc42009a240)
            /usr/local/go1.7/src/testing/testing.go:579 +0x25d
    panic(0x3b5900, 0xc420077af0)
            /usr/local/go1.7/src/runtime/panic.go:458 +0x243
    github.com/micro/go-os/trace.(*clientWrapper).Call(0xc42007baa0, 0x13582f0, 0xc420076538, 0x5de1a0, 0xc420072900, 0x3d7d20, 0xc420084048, 0x0, 0x0, 0x0, ...)
            /Volumes/DATA/Src/Go/src/github.com/micro/go-os/trace/wrapper.go:75 +0x4d4
    github.com/micro/user-srv/proto/account.(*accountClient).Read(0xc4200e29a0, 0x13582f0, 0xc420076538, 0xc420077ac0, 0x0, 0x0, 0x0, 0xc420025f78, 0x2ad73, 0xc420025f48)
            /Volumes/DATA/Src/Go/src/github.com/micro/user-srv/proto/account/account.pb.go:356 +0x145
    git.sillydong.com/chenzhidong/miaosha/api/model/moduser.TestRequest(0xc42009a240)
            /Volumes/DATA/Src/Go/src/git.sillydong.com/chenzhidong/miaosha/api/model/moduser/mod_user_test.go:21 +0x1e7
    testing.tRunner(0xc42009a240, 0x459c58)
            /usr/local/go1.7/src/testing/testing.go:610 +0x81
    created by testing.(*T).Run
            /usr/local/go1.7/src/testing/testing.go:646 +0x2ec
    exit status 2

**Comment by asim** [comment]
https://github.com/micro/go-os/commit/098751f97561dd78ee9dca7193d8a4bd8a849f03

Test now

**Comment by sillydong** [comment]
the panic is gone! Thanks a lot!
