### ISSUE TITLE
Propose to use casbin as the authorization library

### ISSUE THREAD

**Issue by hsluoyz** [micro/go-os#41]
Hi all, I'm the author of [casbin](https://github.com/hsluoyz/casbin), a Go library for authorization based on access control policy. casbin supports multiple access control models like ACL, BLP, RBAC. I'd like to make casbin as a part of go-os authorization. Please let me know if I can provide any help.

**Comment by asim** [comment]
Go-OS is a set of interfaces which can be implemented. You can freely implement something using casbin and share it publicly on github. The micro [explorer](https://micro.mu/explore/) will pick that up and make it easy for others to find.
